 use rh2;
 
CREATE TABLE TB_CARGO (

ID INTEGER AUTO_INCREMENT,
FUNCAO VARCHAR(60),
DEPARTAMENTO VARCHAR(50),
PRIMARY KEY(ID)
);

INSERT INTO TB_CARGO (FUNCAO,DEPARTAMENTO) VALUES ("DESENVOLVEDOR Jr", "T.I");
INSERT INTO TB_CARGO (FUNCAO,DEPARTAMENTO) VALUES ("DESENVOLVEDOR Jr", "T.I");
INSERT INTO TB_CARGO (FUNCAO,DEPARTAMENTO) VALUES ("DESENVOLVEDOR Jr", "T.I");
INSERT INTO TB_CARGO (FUNCAO,DEPARTAMENTO) VALUES ("DESENVOLVEDOR Jr", "T.I");
INSERT INTO TB_CARGO (FUNCAO,DEPARTAMENTO) VALUES ("DESENVOLVEDOR Jr", "T.I");
INSERT INTO TB_CARGO (FUNCAO,DEPARTAMENTO) VALUES ("DESENVOLVEDOR Jr", "T.I");
INSERT INTO TB_CARGO (FUNCAO,DEPARTAMENTO) VALUES ("DESENVOLVEDOR Jr", "T.I");
INSERT INTO TB_CARGO (FUNCAO,DEPARTAMENTO) VALUES ("DESENVOLVEDOR Jr", "T.I");
INSERT INTO TB_CARGO (FUNCAO,DEPARTAMENTO) VALUES ("DESENVOLVEDOR Jr", "T.I");
INSERT INTO TB_CARGO (FUNCAO,DEPARTAMENTO) VALUES ("DESENVOLVEDOR Jr", "T.I");
INSERT INTO TB_CARGO (FUNCAO,DEPARTAMENTO) VALUES ("DESENVOLVEDOR Jr", "T.I");
INSERT INTO TB_CARGO (FUNCAO,DEPARTAMENTO) VALUES ("DESENVOLVEDOR Jr", "T.I");
INSERT INTO TB_CARGO (FUNCAO,DEPARTAMENTO) VALUES ("DESENVOLVEDOR Jr", "T.I");
INSERT INTO TB_CARGO (FUNCAO,DEPARTAMENTO) VALUES ("DESENVOLVEDOR Jr", "T.I");
INSERT INTO TB_CARGO (FUNCAO,DEPARTAMENTO) VALUES ("DESENVOLVEDOR Jr", "T.I");
 
 
CREATE TABLE TB_FUNCIONARIOS (

ID INTEGER  auto_increment,
NOME varchar(35) not null,
SOBRENOME INTEGER,
ENDERECO INTEGER not null,
ID_CARGO INTEGER,
PRIMARY KEY(ID)
FOREIGN KEY (ID_CARGO) REFERENCES TB_CARGO (ID)
);

INSERT INTO  TB_FUNCIONARIOS (NOME, SOBRENOME,SALARIO, ENDERECO)
VALUES
("DAVID", "SALES","1900.00", "RUA XXX"),
("MARIA", "SOUZA", "1800.00", "RUA XXX"),
("LUCAS", "DA SILVA", "2300.00", "RUA XXX"),
("DYLAN", "RODRIGUES", "1100.00",  "RUA XXX"),
("CAIO", "CAMARGO", "5600.00", "RUA XXX"),
("CARLOS", "LIMA","4400.00",  "RUA XXX"),
("JULIA", "SADEK", "1200.00", "RUA XXX"),
("NATASHA", "SCHOLZE","7500.00",  "RUA XXX"),
("CAUE", "MANZONI","1300.00",  "RUA XXX"),
("BRUNA", "DE OLIVEIRA","3500.00",  "RUA XXX"),
("LUIZA", "AZEVEDO","4500.00",  "RUA XXX"),
("DALVA", "NOGUEIRA","6500.00",  "RUA XXX"),
("DIANA", "LIMA","4500.00",  "RUA XXX"),
("ALBERT", "CARL","3500.00", "RUA XXX"),
("CAMILA", "SAM","2000.00",  "RUA XXX");




SELECT * FROM TB_FUNCIONARIOS WHERE SALARIO > 2000;

SELECT * FROM TB_FUNCIONARIOS  WHERE BETWEEN SALARIO 1000 AND 2000;

SELECT * FROM TB_FUNCIONARIOS  WHERE NOME LIKE "C%";

SELECT F.*, C.* FROM TB_FUNCIONARIOS F INNER JOIN TB_CARGO C ON F.ID_CARGO = C.ID;

SELECT F.NOME,C.FUNCAO  FROM TB_FUNCIONARIOS F  INNER JOIN TB_CARGO C ON F.ID_CARGO = C.ID 
WHERE C.FUNCAO = 'DESENVOLVDEDOR Jr';


